version: '3.1'
services:
  demoBackup:
    container_name: postgres-demoBackup
    image: registry.rd.lan/ici/demo-postgres:7.6.3
    volumes:
      - postgresBackupVolume:/opt/bonita/dump
    restart: always
  postgres11:
    build:
      context: "."
    image: registry.rd.lan/bonitasoft/postgres-11
    restart: always
    depends_on:
      - demoBackup
    volumes:
      - postgresBackupVolume:/opt/bonita/dump
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  postgresBackupVolume:

